### ISSUE TITLE
Marker protein search failed!

### ISSUE THREAD

**Issue by aaa-meituo-aaa** [oschwengers/platon#12]
Hi !

when i running platon, it was showed "Marker protein search failed"! what is this mean?

commond line: platon 9_M_contigs.fasta --db /mibi/Wanli/plton/db -o platontest -t 8 --verbose
Options, parameters and arguments:
	db path: /mibi/users/Wanli/plton/db
	use bundled binaries: False
	genome path: /mibi/users/Wanli/gut_micr/test_platon/9_M_contigs.fasta
	output path: /mibi/users/Wanli/gut_micr/test_platon/platontest
	prefix: 9_M_contigs
	mode: accuracy
	characterize: False
	tmp path: /tmp/tmpm92_0thl
	# threads: 8
parse draft genome...
	exclude contig 'NODE_9_length_966_cov_1.577053_cutoff_0', too short (966)
	exclude contig 'NODE_10_length_909_cov_1.908654_cutoff_0', too short (909)
	exclude contig 'NODE_11_length_728_cov_0.471582_cutoff_0', too short (728)
	exclude contig 'NODE_12_length_674_cov_3.328308_cutoff_0', too short (674)
	exclude contig 'NODE_13_length_617_cov_10.677778_cutoff_0', too short (617)
	parsed 30 raw contigs
	excluded 5 contigs by size filter
	analyze 25 contigs
predict ORFs...
	found 474 ORFs
search marker protein sequences (MPS)...
Marker protein search failed!

**Comment by oschwengers** [comment]
Hello @aaa-meituo-aaa ,
it seems that `platon` is not able to find any protein from its internal database. This could be due to the assembly itself (rare species which is not covered very well by the marker proteins (MPS) in the database or this could also be a simple technical issue.

Could please provide the log file along with some more information on the species?

**Comment by ryotag** [comment]
I also have the same error. (This might also be related to #10.)
I'm using macOS.

```
$ platon --db db test.fasta
Marker protein search failed!
$ tail -3 test.log
2020-08-29 08:42:10,751 - main - INFO - ORF detection: # ORFs=4467
2020-08-29 08:42:10,751 - main - INFO - ORF contig filter disabled! # passed contigs=63
2020-08-29 08:42:39,797 - main - ERROR - diamond execution failed! diamond-error-code=-4
```

When I ran diamond itself, it failed as follows.
```
$ diamond blastx -d db/mps -q test.fasta --verbose
.
.
.
Searching alignments... Illegal instruction: 4
```

The release page of diamond v0.9.33 (https://github.com/bbuchfink/diamond/releases/tag/v0.9.33) says "Fixed various issues related to Illegal instruction errors on macOS.".
Because platon uses diamond v0.9.32, macOS seems to suffer from this problem and this might be the reason why platon returns an error.

**Comment by oschwengers** [comment]
@ryotag Thank you very much for the hint, excellent! I'll have a look at that and update the `diamond` version upon successful tests. I'll let you know...

**Comment by ryotag** [comment]
Thanks @oschwengers!
I'm looking forward to it.

**Comment by oschwengers** [comment]
@ryotag a first test with `diamond v2.0.4` was successful on Linux. Unfortunately, I have no access to a MacOS system for testing/debugging purposes. I submitted a PR to Bioconda in order to update `diamond` there as well. Until, the merge is public, you can also use the GitHub-based installation of `platon` containing the latest `diamond` version as explained in the readme. Please, let me know, if this fixes the issue.

**Comment by oschwengers** [comment]
@aaa-meituo-aaa , @ryotag I successfully tested `platon` with `diamond=2.0.4` on Linux. An updated is pushed to BioConda and public. Please, drop me line if this fixes the issue on MacOS, as I don't have any MacOS system in order to debug this myself.

**Comment by ryotag** [comment]
@oschwengers I confirmed that current version of Platon works well on macOS.
Thanks a lot!

**Comment by oschwengers** [comment]
@ryotag Great! Thanks a lot again for the hint and for the quick reply!
