### ISSUE TITLE
Incorporate latest RefSeq Reference Plasmid database files

### ISSUE THREAD

**Issue by tdcollingsworth** [oschwengers/platon#13]
@oschwengers @mr-c @patrick-barth 

Hey, guys!

This tool is great: recent incorporation into our workflow had offered some really insightful perspectives we were struggling to obtain prior to coming across your work. Thank you!

It looks like the RefSeq Plasmid FTP site now contains **eight** "plasmid.*.1.genomic.fna.gz" files and, from 'build-db.sh', it looks like the current database (https://zenodo.org/record/3924529/files/db.tar.gz?download=1) may contain only **six** of these. It appears as though this data were added (2020-07-09) shortly after your publication of the database (2020-06-30), unfortunately. 

Can we confirm or disconfirm what "db.tar.gz" was built using?

If there are now additional "plasmid.*.1.genomic.fna.gz" files available, could we have access to an updated database?

Grateful for all your hard work, I know we're all pulled in a lot of directions right now,
Timothy

**Comment by oschwengers** [comment]
Hi @tdcollingsworth ,
thanks a lot for the nice words, very much appreciated! Yes, I can confirm that the last db release was built in April using only the 6 plasmid files which were available back then. Of course, we're keen to keep the databases up-to-date. However, this implies some larger computations (recalculation of the RDS scores & thresholds). That's why this will definitely take a while. But I put this on my list and let you know once its done. Thanks again and best regards!

**Comment by oschwengers** [comment]
Hi @tdcollingsworth , it took a while, but I just released a new version [1.5.0](https://github.com/oschwengers/platon/releases/tag/v1.5.0). A related db is available at https://zenodo.org/record/4066768.

The database is built with RefSeq release 202 comprising 20,041 complete chromosomes and 18,795 complete plasmids.
It might take a while until the update makes it through BioConda.

I hope you find this update useful, the overall accuracy for our test data further increased to >= 85 % 
Best reagards!

**Comment by tdcollingsworth** [comment]
Hey, @oschwengers -

This is great news -- congratulations on the release and, especially, the increase in overall accuracy!

In appreciation,

Timothy
