### ISSUE TITLE
Error: No module named 'platon.platon'

### ISSUE THREAD

**Issue by androga2** [oschwengers/platon#21]
Hi, 

Thank you so much for Platon software!

The installation of program was successful, I followed these steps:

```
$ conda install -c conda-forge -c bioconda -c defaults platon

$ python3 -m pip install --user platon
```

But, when I run the program, I get this error:

```
$ platon
Traceback (most recent call last):
  File "/home/life/miniconda3/bin/platon", line 6, in <module>
    from platon.platon import main
ModuleNotFoundError: No module named 'platon.platon'
```

How can I fix this bug?

Cheers

Andrea

**Comment by oschwengers** [comment]
Hi, you do not need to install the software via Conda *and* Pip - it's either or, one is sufficient but Conda is the most convenient solution.

However, there was a typo in the readme regarding the PyPI path. For namespace reasons it's `cb-platon` instead of `platon`. This is fixed now (https://github.com/oschwengers/platon/commit/7671045ca493679787a8d50d6508a15ccb3b7021). Thanks for pointing out. 

The issue should be solved by this. Just in case it remains, please do not hesitate to re-open it.
Best regards!
