### ISSUE TITLE
Platon is Time-Intensive

### ISSUE THREAD

**Issue by joshuakirsch** [oschwengers/platon#25]
Hi, I'm using platon for the first time with a very large metagenome (330k contigs). Although I specified 50 threads (which our computer has) when calling platon, the program still takes ~3-4 days to complete. The most time intensive part appears to be characterizing contigs. Any tips on how to speed things up?

Thanks for making a great tool!

command line arguments: platon --db platon_db --output platon_supercent --threads 50  --verbose allContigs_sorted.fa
Version 1.6
Installed with Conda

**Comment by oschwengers** [comment]
Hi! Actually, Platon was not designed for the analysis of metagenomes but draft genomes of bacterial isolates.
However, the workflow should in principle work fine with metagenomes, too though the initial gene prediction by Prodigal runs in a single genome mode instead of a metagenome mode. I could add a `--meta` flag in an upcoming release to address this.
But the characterization workflow is indeed rather computational intensive and thus Platon will take its time.

I guess there is no simple solution to speed things up. Maybe you can just split the contig set into chunks and analyze them in parallel on a compute cluster if you have access to one?

**Comment by oschwengers** [comment]
@joshuakirsch I've added a `--meta` flag triggering the internal gene prediction being executed in metagenome mode (via Prodigal).
As by using `--meta` there is no actual inherent relation between them anymore, this streamlines the supposed idea of separating and analyzing input contigs in smaller chunks and thus allow horizontal scalability as well.

**Comment by joshuakirsch** [comment]
Thanks! I appreciate the quick response and fix.

**Comment by oschwengers** [comment]
You're welcome and thanks for bringing this up. This will be public in an upcoming release that will also include a db update. Until then, you can install this fix via `python3 -m pip install <path-to-repo>` with `<path-to-repo>` pointing to local copy of this repo. I'll close this for now, but please, do not hesitate to reach out and/or re-open this in any case.
