### ISSUE TITLE
The number of contigs in plasmid.fasta is not the same as the number of contigs in .tsv 

### ISSUE THREAD

**Issue by xuanji2017** [oschwengers/platon#28]
Hi, 
I found that the number of contigs in plasmid.fasta is not the same as the number of contigs in .tsv. The number of contigs in my .tsv file is 112,598 but the number of contigs in plasmid.fasta is 111,936. Do you have any idea what the problem is? which one should I use? And also the contig number in plasmid.fasta+ the contig number in chromosome.fasta < the total number of the contigs. What are the others? Thanks a lot!

Best
Xuanji

**Comment by oschwengers** [comment]
Hi @xuanji2017,
thanks for reporting. This seems rather odd and has not been reported so far. Due to the large number of contigs I infere that this is a metagenome assembly? Could you provide more information like the executed version, parameters, options, etc?
The log file would certainly help to figure out what happened (maybe GNU zipped?)

**Comment by oschwengers** [comment]
Hi @xuanji2017 ,
is this still active? Otherwise, I'd close this for now.

**Comment by xuanji2017** [comment]
yes, please. Thanks lot!


Xuanji Li
postdoc

University of Copenhagen
Faculty of Science
Section for Microbiology
Universitetsparken 15, bldg. 1
DK2100 Copenhagen

 +45 71401828



________________________________
